# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef88ca6d2fdffde24d82bf1d4b397956138656ec1d6c82f54dfde2ba40e2d10e41118835824a07beeba15e014ec8914f4e6e077b0e888437761897924a01f2e9

test:
  secret_key_base: 3d3d5b558d4103c49942b282435d9584416606083141ff514641cfbdfbb2c6b5b87166520fce73d83a892950dcc6109b19a9fc2bae3cfc1ec18e48559b16f5ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
